ContactBundle\Entity\Contact:
    type: entity

    inheritanceType: JOINED
    discriminatorColumn:
        name: type
        type: integer
    discriminatorMap:
        1: Friend
        2: Ennemy

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255

        surname:
            type: string
            length: 255

        birthDate:
            type: date

    oneToMany:
        commWay:
            targetEntity: CommunicationWay
            mappedBy: contact
            cascade: [ persist, remove ]

    lifecycleCallbacks: {  }
