ContactBundle\Entity\Ennemy:
    type: entity

    associationOverride:
        tabCommWays:
            joinTable:
                name: ennemy_tabcommways
                joinColumns:
                    ennemy_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tabCommWays_id:
                        referencedColumnName: id
            cascade: [ persist, merge, detach ]

    fields:
        ennemySince:
            type: date

    lifecycleCallbacks: {  }
