ContactBundle\Entity\Friend:
    type: entity

    associationOverride:
        tabCommWays:
            joinTable:
                name: friend_tabcommways
                joinColumns:
                    friend_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tabCommWays_id:
                        referencedColumnName: id
            cascade: [ persist, merge, detach ]

    fields:
        friendSince:
            type: date

    lifecycleCallbacks: {  }

